### ISSUE TITLE
Chocolatey hosed nupkg does not match nuspec

### ISSUE THREAD

**Issue by basictheprogram** [ericjaystevens/chocolatey-Veeam-Endpoint-Backup-FREE#11]
The nupkg host at chocolatey.org does not match the nuspec in the github source.

Does the package need to be rebuilt?

I mentioned this in the Disqus comment about 1 month ago.

Here is the live chocolateyinstall.ps1 
```
$toolsDir   = $(Split-Path -Parent $MyInvocation.MyCommand.Definition)
$packageName = 'VeeamEndpointBackup'
$installerDir = Join-Path $toolsDir 'installer'
$downloadURL = 'https://download5.veeam.com/VeeamEndpointBackup_1.5.0.306.zip'
$installer = 'VeeamEndpointBackup_1.5.0.306.exe'
 
 
Install-ChocolateyZipPackage $packageName -url $downloadURL -UnzipLocation $installerDir
 
$packageArgs = @{
  packageName   = $installer
  fileType      = 'exe'
  file          = "$installerDir\$installer"
  silentArgs    = '/silent'
  ValidExitCodes = @(0,1000,1001)
}
Install-ChocolateyInstallPackage @packageArgs 
```
Here is the chocolateyinstall.ps1 from github
```
$toolsDir   = $(Split-Path -Parent $MyInvocation.MyCommand.Definition)
$packageName = 'VeeamAgentWindows'
$packageVersion = '2.0.0.700'
$installerDir = Join-Path $toolsDir 'installer'
$downloadURL = "https://download5.veeam.com/$($packageName)_$packageVersion.zip"
$installer = "$($packageName)_$packageVersion.exe"

$zipArgs = @{
	packageName   = $packageName
	url           = $downloadURL
	unzipLocation = $installerDir
	checksum      = '5430baed6bf5711e89b0c93456949597'
	checksumType  = 'md5'
}

Install-ChocolateyZipPackage @zipArgs

$packageArgs = @{
	packageName   = $installer 
	fileType      = 'exe'
	file          = "$installerDir\$installer"
	silentArgs    = '/silent /accepteula'
  ValidExitCodes = @(0,1000,1101)
}

Install-ChocolateyInstallPackage @packageArgs 
```

**Comment by ericjaystevens** [comment]
That't correct I haven't been able to get the package through the vetting process on chocolaty.org In part because it requires a manual override because issue #1, also it was failed moderation because the .net dependency is not stated properly in the package. In short I need to resubmit it.

**Comment by basictheprogram** [comment]
I assume you mean #5 ? #1 is closed. I just submitted a PR for #5.

**Comment by basictheprogram** [comment]
Using a pristine Windows 7 VM and testing the 2.0.x package it doesn't look like it needs .NET dependency. Am I missing something?

**Comment by basictheprogram** [comment]
Using https://github.com/chocolatey/chocolatey-test-environment the package does fail.
  * [choco.summary.log](https://github.com/ericjaystevens/chocolatey-Veeam-Endpoint-Backup-FREE/files/1423750/choco.summary.log)
  * [chocolatey.log](https://github.com/ericjaystevens/chocolatey-Veeam-Endpoint-Backup-FREE/files/1423751/chocolatey.log)

Running the installer by hand it complained the Vagrant testing environment needed to be rebooted.
Rebooted and now I get this dialog.

<img width="304" alt="chocolatey-test-environment_default_1509145556197_81845__sahara-sandbox___running_" src="https://user-images.githubusercontent.com/6723257/32130909-08351916-bb67-11e7-8941-6cae42ab7df3.png">

I'll submit a PR to add the .NET dependency.

**Comment by basictheprogram** [comment]
Got dependencies working-ish. 
Problem. 
If you install the chocolatey package dotnet4.5.2 it wants to reboot. I do not know how to handle a reboot when the reboot is caused by a dependency. Any ideas?

Google Group [thread](http://bit.ly/2xumf6V) talks about it but no official response or work around.

Maybe just document it?

Ask for exception?

I'm guessing the verification process will fail.

**Comment by basictheprogram** [comment]
Using https://github.com/chocolatey/chocolatey-test-environment, unzipping VeeamAgentWindows_2.0.0.700.zip, and running VeeamAgentWindows_2.0.0.700.exe I get the ".NET Framework 4.5.2 is missing" dialog.

The virtualbox box is pretty out dated.

Applying the latest Window Updates and rebooting allows the VeeamAgentWindows_2.0.0.700.exe to install without a problem.

I propose documenting the fact that  .NET 4.5.2 is required, but chocolatey does not handles dependency that needs a reboot, ask for an exception to pass the package verification process.

I've done a PR with a <description> I think explains the problem and a work around.

**Comment by basictheprogram** [comment]
https://github.com/chocolatey/chocolatey-test-environment installs [.NET 4.0](https://github.com/chocolatey/chocolatey-test-environment/blob/master/shell/InstallNet4.ps1)  so maybe it's safe to assume if people are running a modern version of Chocolatey a proper version of .NET is installed?

**Comment by ericjaystevens** [comment]
posted to chocolatey.org as [veeam-agent](https://chocolatey.org/packages/veeam-agent)
